image: "rust:latest"

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

check:listener-example:
  script:
  - cd examples/tcp-listener && cargo check --verbose

check:client-example:
  script:
  - cd examples/tcp-client && cargo check --verbose

pages:
  script:
  - cargo doc
  - mv target/doc/ public/
  artifacts:
    paths:
    - public
  only:
    - master
