[package]
name = "futures-retry"
version = "0.3.2"
authors = ["mexus <gilaldpellaeon@gmail.com>", "Sylwek <sylwesterrapala@outlook.com>"]
description = "Retry your Futures and Streams and Sinks!"
license = "MIT/Apache-2.0"
keywords = ["tokio", "futures", "retry"]
repository = "https://gitlab.com/mexus/futures-retry"
documentation = "https://docs.rs/futures-retry/"
readme = "README.md"
edition = "2018"

[dependencies]
futures = "0.1.21"
tokio-timer = "0.2.1"

[dev-dependencies]
tokio = "0.1.12"
tokio-fs = "0.1"
