[package]
name = "futures-retry"
version = "0.1.0"
authors = ["mexus <gilaldpellaeon@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
futures = "0.1"
tokio-timer = "0.1"

[dev-dependencies]
tokio = "0.1"
